### ISSUE TITLE
make DPDK=1 MLX5=1 error

### ISSUE THREAD

**Issue by caoxiaogang96** [p4lang/p4app-switchML#9] opened 2022-03-24 14:14 UTC
When I compile and install client_lib with command 'make DPDK=1 MLX5=1', I encounter four problems:
1) error: unknown subcommand：get-url，which is in dev_root/client_lib/Makefile:154
2) fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
3) Package absl_base was not found in the pkg-config search path. Perhaps you should add the directory containing `absl_base.pc' but I have compiled and installed absl-cpp in dev_root/third_party/grpc/third_party
4) /dev_root/build/lib/libswitchml-client.a: Index cannot be added: no symbol can be archived; Run ranlib to add one

How can I fix them?

**Comment by AmedeoSapio** [comment] 2022-04-29 02:56
Hi, 
the first two errors should be fixed if you update git to a newer version (2.20+).
For the other two, I cannot reproduce them and it is difficult to solve them without knowing your environment. Please try using the available dockerfiles, which should provide a more predictable environment. If you still have problems, I need to know more about your environment (like OS and gcc versions).

The MLX5 flag is not needed to compile the client library, but only for dpdk and examples. 
You can try to compile using the makefile in the dev_root folder, which can take care of compiling also the third party libraries before compiling the client library.

**Closed by AmedeoSapio** 2022-04-29 02:56 UTC
